"""
Pydantic output models for CrewAI agent responses.

Bu modeller demo_simulation.py içindeki serbest metin çıktıları production
tarafında deterministik ve doğrulanabilir hale getirir.

Demo:
    SCORE: 74
    CATEGORY: Gündem
    Summary generated by Ollama:
      - ...

Production:
    ScoreOutput          -> article_id + score
    CategorizationOutput -> article_id + max 3 kategori
    SummaryOutput        -> article_id + TL;DR metni

CrewAI task'ları `output_pydantic` parametresiyle bu modelleri kullanır. Böylece
LLM yanlış formatta yanıt üretirse hata erken yakalanır; DB araçlarına gidecek
alan adları da açıkça belirlenmiş olur.
"""

from pydantic import BaseModel, Field


class ScoreOutput(BaseModel):
    """
    Scoring agent çıktısı.

    route_by_score düğümü bu puanı doğrudan CrewAI cevabından değil DB'den okur,
    fakat agent çıktısının bu modelle sınırlandırılması prompt disiplinini artırır.
    """
    article_id: int = Field(..., description="İlgili makalenin ID'si")
    score: int = Field(
        ..., ge=1, le=100,
        description="1-100 arası kalite puanı"
    )


class CategorizationOutput(BaseModel):
    """
    Categorization agent çıktısı.

    demo_simulation.py tek kategori gösterir; production tarafında en fazla 3
    kategoriye izin verilir. Bu üst sınır hem Pydantic modelde hem de DB tool'da
    ayrıca uygulanır.
    """
    article_id: int = Field(..., description="İlgili makalenin ID'si")
    categories: list[str] = Field(
        ..., max_length=3,
        description="En fazla 3 kategori adı listesi"
    )


class SummaryOutput(BaseModel):
    """
    Summarization agent çıktısı.

    Summary tek string olarak tutulur; ister "- madde" satırlarıyla, ister kısa
    paragraf formatında saklanabilir. Prompt tarafı TL;DR maddelerini zorlar.
    """
    article_id: int = Field(..., description="İlgili makalenin ID'si")
    summary: str = Field(
        ..., description="3-4 maddelik TL;DR özet"
    )
